---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: (( concat tweed.prefix tweed.instance ))
  labels:    (( grab tweed.k8s.labels ))
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
  selector: (( grab tweed.k8s.labels ))
