---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: (( grab tweed.k8s.ns ))
  labels:    (( grab tweed.k8s.labels ))
spec:
  replicas: 1
  selector:
    matchLabels: (( grab tweed.k8s.labels ))
  template:
    metadata:
      labels: (( grab tweed.k8s.labels ))
    spec:
      containers:
        - name:  redis
          image: (( concat "redis:" tweed.ops.version || tweed.default.version ))
          ports:
            - name: redis
              containerPort: 6379
          command:
            - redis-server
            - --requirepass
            - (( vault tweed.vault "/auth:password" ))
            - --dir
            - /data
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis
