---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: (( concat tweed.prefix tweed.instance ))
  labels: (( grab tweed.k8s.labels ))
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
  selector: (( grab metadata.labels ))
